package generic

import (
	"testing"
)

// Generated by ChatGPT
func TestSharedPrefix(t *testing.T) {
	tests := []struct {
		str1, str2, expected string
	}{
		{"abcdef", "abcxyz", "abc"},
		{"apple", "apricot", "ap"},
		{"", "abc", ""},
		{"xyz", "", ""},
		{"123", "123", "123"},
	}

	for _, test := range tests {
		actual := SharedPrefix(test.str1, test.str2)
		if actual != test.expected {
			t.Errorf("Expected '%s', got '%s'", test.expected, actual)
		}
	}
}

// Generated by ChatGPT
func TestSharedSuffix(t *testing.T) {
	tests := []struct {
		str1, str2, expected string
	}{
		{"abcdef", "xyzdef", "def"},
		{"hello", "worldo", "o"},
		{"", "abc", ""},
		{"xyz", "", ""},
		{"123", "123", "123"},
	}

	for _, test := range tests {
		actual := SharedSuffix(test.str1, test.str2)
		if actual != test.expected {
			t.Errorf("Expected '%s', got '%s'", test.expected, actual)
		}
	}
}
